FROM maven:latest

WORKDIR /usr/src/spring-boot-docker-ci-example
COPY pom.xml .
RUN mvn -B -f pom.xml -s /usr/share/maven/ref/settings-docker.xml dependency:resolve
COPY . .
RUN mvn -B -s /usr/share/maven/ref/settings-docker.xml package -DskipTests

ENTRYPOINT ["java", "-jar", "/usr/src/spring-boot-docker-ci-example/target/spring-boot-docker-ci-example-0.0.1-SNAPSHOT.jar"]